/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class native_implement_Invoker */

#ifndef _Included_native_implement_Invoker
#define _Included_native_implement_Invoker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     native_implement_Invoker
 * Method:    InvokeMPIHeatConduct
 * Signature: (Ljava/lang/String;[[[II)V
 */
JNIEXPORT void JNICALL Java_native_1implement_Invoker_InvokeMPIHeatConduct
  (JNIEnv *, jobject, jstring, jint, jint, jint, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
